{% set name = "neptune-sklearn" %}
{% set version = "0.9.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/neptune-ai/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 250755408b6a7a78e5ddb3c206a12cc8fbc7608e4ef502678bbc5169fd22312f

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - neptune-client >=0.9
    - python >=3.6
    - scikit-learn >=0.24.1
    - scikit-plot >=0.3.7
    - yellowbrick >=1.3

test:
  imports:
    - neptune_sklearn
    - neptune_sklearn.impl

about:
  home: https://neptune.ai/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Neptune Client integration with Scikit-Learn
  doc_url: https://github.com/neptune-ai/neptune-sklearn/blob/master/README.md
  dev_url: https://github.com/neptune-ai/neptune-sklearn

extra:
  recipe-maintainers:
    - aniezurawski
    - HubertJaworski
    - pitercl
    - PiotrJander
    - shnela
    - pkasprzyk
